astronomer/ap-vendor

- curator/Dockerfile
**Which images are updated by this PR?**:
**Checklist** (required)
**Additional notes for your reviewer**:
> Migrate Dockerfile to astronomerinc/ap-base:3.11.5-3

- curator/Dockerfile
**Which issue this PR fixes**:
**Summary of changes**:
**Which images are updated by this PR?**:
**Checklist** (required)
**Additional notes for your reviewer**:
> Bump sqlite-libs from edge

- fluentd/include/Gemfile
Resolves CVE https://github.com/astronomer/ap-vendor/network/alert/fluentd/include/Gemfile/activesupport/open
@andriisoldatenko do you have a way to test this image?
> Resolve CVE-2020-8165 on fluentd

- elasticsearch/Dockerfile
- kibana/Dockerfile
fix astronomer/issues#1569
**Which issue this PR fixes**:
**Summary of changes**:
**Which images are updated by this PR?**:
**Checklist** (required)
> patch CVEs by upgrading dbus in es and kibana images

- grafana/Dockerfile
- grafana/include/nats-dash.json
- grafana/include/stan-dash.json
fix https://github.com/astronomer/issues/issues/1415
**Which issue this PR fixes**:
**Summary of changes**:
**Which images are updated by this PR?**:
**Checklist** (required)
**Additional notes for your reviewer**:
depend on https://github.com/astronomer/astronomer/pull/754
> Add nats dashboard

- .circleci/config.yml
- .circleci/config.yml.j2
- .github/PULL_REQUEST_TEMPLATE.md
This PR changes the default branch to `main`. I edited the j2 template and ran the generate script. Does this look right @sjmiller609?
> Change default branch to main

- .circleci/config.yml
- .circleci/config.yml.j2
fix https://github.com/astronomer/issues/issues/1614
> cache trivy database only on daily basis instead of forever

- Makefile
This just adds a Makefile with a few developer workflow related targets. There are no changes to any generated images.
> Add Makefile with two helper targets

- .circleci/config.yml
- .circleci/config.yml.j2
Add the docker.io context after deleting the variables from the project local vars.
> Add docker.io context

- .circleci/config.yml
- .circleci/config.yml.j2
- .pre-commit-config.yaml
- Makefile
- bin/check_version.py
- bin/docker-build.sh
- bin/docker-push.sh
- bin/generate_circleci_config.py
- bin/trivy-scan.sh
- grafana/include/airflow-database-activity.json
- statsd-exporter/include/mappings.yml
- statsd-exporter/test/test.py
The main purpose of this branch was to prevent quay.io images from being overwritten. I have solved this. While digging into the problem I reworked the CI process to rely on external scripts vs yaml-embedded scripts. This gives us more confidence that these are syntactically correct and takes steps towards centralizing these, since they are easier to manage as files.
- Move embedded yaml scripts out to per-file scripts in bin directory
- Move circleci config generation script into bin directory
- Improve pre-commit configs and add new hooks
- Improve Makefile helper targets
- Improve wording in various places
- Run all pre-commit hooks on entire repo, which rewrote some python and yaml in some of these projects
- Manually fixed some typos reported by codespell
Related to …
> 2868 do not overwrite tags

- nginx-es/Dockerfile
https://github.com/astronomer/issues/issues/1290
> ap-nginx-es: image should be created with a non root user

- .circleci/config.yml
- .circleci/config.yml.j2
- .pre-commit-config.yaml
- bin/docker-build.sh
- bin/docker-push.sh
Bump some CI stuff, some of which had been done in a different branch that has yet to be merged. I'd like to bring these changes in while waiting for issues on that branch to be resolved.
> Bump and improve CI

- fluentd/Dockerfile
resolves https://github.com/astronomer/issues/issues/1290
> ap-fluentd: image should be created with a non root user

- .github/PULL_REQUEST_TEMPLATE.md
Added missing image list to Issue Template 
> added missing images in PR template

- awsesproxy/Dockerfile
Added valid comment for code checkout to particular commit
astronomer/issues#3820
> added comment for checkout commit id

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/trivy-scan.sh
Minor CI maintenance and improvements. Address <https://github.com/aquasecurity/trivy/discussions/1515>
> Bump some CI image versions. Use var for docker version.

- pgbouncer/Dockerfile
Fixes an issue while building pgbouncer 
update pgbouncer to 1.17.0
changes to ap-base
> add openssl dev tools for pgbouncer compilation

- grafana/trivyignore
ignoring below CVE 
CVE-2022-27191
> add trivyignore for grafana

- alertmanager/trivyignore
- kubed/trivyignore
- node-exporter/trivyignore
Ignore x/crypto golang library vulnerability triggered by trivy scanner
add trivyignore file
> ignore CVE which does not impact astronomer

- postgres-exporter/trivyignore
- prometheus/trivyignore
ignore CVE which does not impact prometheus and postgres exporter
added trivyignore for CVE-2022-27191 
> ignore CVE which does not impact prometheus and postgres exporter

- README.md
Document details about how the repo is used.
> Add details about how ap-vendor repo is used

- .circleci/config.yml
- .circleci/config.yml.j2
Removing Snyk Scan for security scanning.
https://github.com/astronomer/issues/issues/4815
> Removing Snyk Docker Image Scan

- .circleci/config.yml
- .circleci/config.yml.j2
Revert Changes with Trivy Scan
> Revert changes with trivy scan

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/docker-operations.py
Now, publishing the `latest` tag when merge to `master`.
https://github.com/astronomer/issues/issues/5314
> Push `latest` tag with each version

- .pre-commit-config.yaml
- .prettierignore
- bin/check_version.py
- bin/docker-operations.py
- bin/generate_circleci_config.py
- bin/generate_docker_compose.py
- bin/test.py
- statsd-exporter/test/test.py
Fixing image push to allow multiple tags to push,
https://github.com/astronomer/issues/issues/5314
> Fixing image push

- postgresql/trivyignore
exclude cve in postgresql scanning
NA
> exclude cve in postgresql scanning

- git-sync/Dockerfile
- git-sync/test.yaml
update gitsync user permission and version
NA
> update gitsync user permission and version

- .circleci/continue-config.yml
- .circleci/continue-config.yml.j2
remove twistcli ignore from ap-vendor since we longer hold the subscription 
Do not merge this PR until this text is replaced with links to related issues if one exists, or else this section is deleted.
> remove twistcli config
